# Copyright 2016 Google Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

sudo: required

language: java

services:
  - docker

jdk:
  - oraclejdk8

branches:
  only:
  - master
  - travis_remote

install:
  # download Cloud SDK
  - wget https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-137.0.0-linux-x86_64.tar.gz
  - tar -xzvf google-cloud-sdk-137.0.0-linux-x86_64.tar.gz
  - export PATH=$PWD/google-cloud-sdk/bin:$PATH
  - export CLOUDSDK_CORE_DISABLE_USAGE_REPORTING=true
  # update all Cloud SDK components
  - gcloud components update -q
  # do not run remote tests for pull requests
  - |
    if [ $TRAVIS_PULL_REQUEST = 'false' ]; then
      export DO_REMOTE=true
    else
      export DO_REMOTE=false
    fi
  - echo DO_REMOTE = $DO_REMOTE
  - |
    if $DO_REMOTE; then
      # decrypt the tavis-app-maven-plugin Cloud SDK project service account key
      openssl aes-256-cbc -K $encrypted_ca118b112eec_key -iv $encrypted_ca118b112eec_iv -in config/travis-app-maven-plugin-caac78288652.json.enc -out config/travis-app-maven-plugin-caac78288652.json -d
      # set Cloud SDK CLI authentication
      gcloud auth activate-service-account --key-file config/travis-app-maven-plugin-caac78288652.json
      # set default project
      gcloud config set project travis-app-maven-plugin
    fi

script:
  # execute regular local build
  - mvn clean verify -B -V -q
  # execute remote tests
  - |
    if $DO_REMOTE; then
      # deploy image to gcr
      image=gcr.io/travis-app-maven-plugin/jetty:`date +%s`
      docker tag jetty:9.4 $image
      # do the remote test
      gcloud docker -q -- push $image && mvn clean verify -Ptest.remote -Djetty.test.image=$image -B -q
    fi

after_script:
  - |
    if $DO_REMOTE; then
      # cleanup deploy image
      gcloud docker rmi $image
    fi